### ISSUE TITLE
3. As a user, I want to set up a new shopping list so I can start tracking purchased items.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-9-smart-shopping-list#3]
A shopping list consists of a set of items associated with a user’s token. Creating a new list consists of the following sequence:

* Generate a new, unique token
* Save the token to `localStorage`
* Show the user the list view

The following script should be used to generate a suitable token: `src/lib/tokens.js`

AC:

* For users who do not already have a token/list, a button or link exists on the home screen that allows them to create a new list
* Clicking the button/link generates a new token and saves it to `localStorage`
* Once the token has been created and saved, the user is redirected to the "list" view

**Comment by stacietaylorcima** [comment]
Eventually, the `welcome/home` page will look like the following [wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/welcome-screen.png).

That being said, don't try to build this whole UI because it will be tackled in other stories. So, for this story, it's sufficient just to have a simple "create list" button.

**Comment by sicunchen** [comment]
- [ ] create a welcome component

- [ ] use a useEffect hook with an empty dependency list to check if a token exists when the component first mounts

- [ ] if the token exists, redirect the user to the list view, otherwise present a "create a new list" button

- [ ] create a button with a click event handler that generates and saves a token when user clicks. We also need to redirect to the list view inside the event handler.
